version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - docker --version

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t myapp:latest .

