---
version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    IMAGE_REPO_NAME: myapp
phases:
  install:
    runtime-versions:
      docker:20
    commands:
      - echo "Installing dependencies..."
      - echo "Docker version:"
      - docker --version
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION/$IMAGE_REPO_NAME"
      - echo "ECR URI is $ECR_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login
        --username AWS --password-stdin $ECR_URI
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:=latest}
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI:$IMAGE_TAG
      - echo "Preparing Helm chart..."
      - mkdir -p deploy
      - sed "s|IMAGE_PLACEHOLDER|$ECR_URI:$IMAGE_TAG|g" helm/deployment.yaml >
        deploy/deployment.yaml
      - echo "Build & Docker push completed successfully!"
artifacts:
  files:
    - deploy/deployment.yaml



