apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer   # creates an external ELB to access the app
  selector:
    app: my-app        # must match labels in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # external port
      targetPort: 3000 # container port
